In [1]:
import torch

In [2]:
x1 = torch.randn(7,8)
y1 = torch.randn(7,8)
z1 = torch.randn(7,8)
print(x1)
print(y1)
print(z1)

tensor([[ 2.5992e+00,  3.1874e-01,  1.9321e-01, -1.5677e+00, -5.5336e-01,
         -1.1999e+00,  1.2652e+00,  1.5683e+00],
        [-2.4046e+00,  4.7404e-02,  5.2272e-01, -3.9687e-01, -8.0782e-01,
          9.4035e-01, -9.1001e-01,  4.6077e-01],
        [-6.9654e-01,  7.1279e-01,  5.3389e-01, -1.2092e+00,  8.7253e-01,
          1.3390e+00,  1.0117e+00, -7.5706e-01],
        [-2.1168e+00, -1.6472e+00,  3.9818e-01,  1.5909e-01,  1.0306e+00,
          2.2321e-01, -4.7506e-02,  1.6338e+00],
        [-7.2276e-01, -2.4106e-01, -4.9481e-02,  9.5644e-01,  6.7302e-01,
         -1.1554e+00, -8.7001e-01, -1.2692e+00],
        [-5.3394e-01,  9.5333e-01, -1.3250e+00, -2.3842e+00, -1.2065e-01,
         -7.1137e-02, -7.6430e-03,  5.0357e-01],
        [ 6.3820e-01, -7.1720e-01, -1.3266e+00, -1.4336e+00,  1.3674e+00,
         -1.1058e+00,  2.9437e-01, -3.2239e-04]])
tensor([[-1.0368, -0.4354,  0.3554, -0.0941,  0.3304,  0.0986,  0.0350, -0.3964],
        [ 0.2077, -0.8574, -0.4166,  0.6293,  1.7161,  0

In [3]:
# 1. max of entire tensor (torch.max(input) → Tensor)
m1 = torch.max(x1)
print(m1)

tensor(2.5992)


In [4]:
# 2. max along a dimension (torch.max(input, dim, keepdim=False, *, out=None) → (Tensor, LongTensor))
m1, idx1 = torch.max(x1,0)
print(m1)
print(idx1)

tensor([2.5992, 0.9533, 0.5339, 0.9564, 1.3674, 1.3390, 1.2652, 1.6338])
tensor([0, 5, 2, 4, 6, 2, 0, 3])


In [5]:
# 2-2
m1, idx1 = torch.max(input=x1,dim=0)
print(m1)
print(idx1)

tensor([2.5992, 0.9533, 0.5339, 0.9564, 1.3674, 1.3390, 1.2652, 1.6338])
tensor([0, 5, 2, 4, 6, 2, 0, 3])


In [6]:
# 2-3
m1, idx1 = torch.max(x1,0,False)
print(m1)
print(idx1)

tensor([2.5992, 0.9533, 0.5339, 0.9564, 1.3674, 1.3390, 1.2652, 1.6338])
tensor([0, 5, 2, 4, 6, 2, 0, 3])


In [7]:
# 2-4
m1, idx1 = torch.max(x1,dim=0,keepdim=True)
print(m1)
print(idx1)

tensor([[2.5992, 0.9533, 0.5339, 0.9564, 1.3674, 1.3390, 1.2652, 1.6338]])
tensor([[0, 5, 2, 4, 6, 2, 0, 3]])


In [8]:
# 2-5
p1 = (m1,idx1)
torch.max(x1,0,False,out=p1)
print(p1[0])
print(p1[1])

tensor([2.5992, 0.9533, 0.5339, 0.9564, 1.3674, 1.3390, 1.2652, 1.6338])
tensor([0, 5, 2, 4, 6, 2, 0, 3])


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: UserWarning: An output with one or more elements was resized since it had shape [1, 1, 8], which does not match the required output shape [1, 8].This behavior is deprecated, and in a future PyTorch release outputs will not be resized unless they have zero elements. You can explicitly reuse an out tensor t by resizing it, inplace, to zero elements with t.resize_(0). (Triggered internally at  /pytorch/aten/src/ATen/native/Resize.cpp:23.)
  This is separate from the ipykernel package so we can avoid doing imports until


In [9]:
# 2-6
p1 = (m1,idx1)
torch.max(x1,0,False,out=p1)
print(p1[0])
print(p1[1])

tensor([2.5992, 0.9533, 0.5339, 0.9564, 1.3674, 1.3390, 1.2652, 1.6338])
tensor([0, 5, 2, 4, 6, 2, 0, 3])


In [10]:
# 3. max(choose max) operators on two tensors (torch.max(input, other, *, out=None) → Tensor)
t1 = torch.max(x1,y1)
print(t1)

tensor([[ 2.5992e+00,  3.1874e-01,  3.5539e-01, -9.4146e-02,  3.3041e-01,
          9.8647e-02,  1.2652e+00,  1.5683e+00],
        [ 2.0769e-01,  4.7404e-02,  5.2272e-01,  6.2930e-01,  1.7161e+00,
          9.4035e-01,  2.8304e-01,  4.6077e-01],
        [-6.9654e-01,  7.1279e-01,  5.3389e-01, -1.8491e-01,  1.4375e+00,
          1.9944e+00,  1.6396e+00,  7.3542e-01],
        [ 3.8209e-01, -4.7967e-01,  3.9818e-01,  1.5909e-01,  1.9092e+00,
          2.2321e-01,  1.6617e+00,  1.6338e+00],
        [-7.2276e-01, -2.4106e-01,  2.9941e-01,  9.5644e-01,  6.7302e-01,
          2.7525e-02,  8.6854e-01, -1.2692e+00],
        [-4.1625e-01,  9.5333e-01,  5.2090e-01, -4.4895e-01,  3.8453e-01,
          8.6989e-01, -7.6430e-03,  5.1514e-01],
        [ 6.3820e-01,  1.7197e+00, -1.3266e+00, -1.1955e+00,  1.3674e+00,
          1.0497e-01,  2.9437e-01, -3.2239e-04]])


In [11]:
dataset1 = "abcdefghijklmnopqrstuvwxyz1234567890"

In [12]:
for datapoint1 in dataset1:
  print(datapoint1)

a
b
c
d
e
f
g
h
i
j
k
l
m
n
o
p
q
r
s
t
u
v
w
x
y
z
1
2
3
4
5
6
7
8
9
0
